apiVersion: v1
kind: Service
metadata:
  name: sample-backend-service
spec:
  type: ClusterIP
  selector:
    app: sample-backend-deployment
  ports:
    - name: sample-backend-port
      port: 80
      targetPort: 80
