apiVersion: v1
kind: Service
metadata:
  name: sample-frontend-service
spec:
  type: ClusterIP
  selector:
    app: sample-frontend-deployment
  ports:
    - name: sample-frontend-port
      port: 80
      targetPort: 80
